// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPGqdlE9HmRe9jiapHxeJjwOZfOwBHsCA',
    appId: '1:887930857034:web:ad74340fecb917fee628b3',
    messagingSenderId: '887930857034',
    projectId: 'my-web-app-cc2b0',
    authDomain: 'my-web-app-cc2b0.firebaseapp.com',
    databaseURL: 'https://my-web-app-cc2b0-default-rtdb.firebaseio.com',
    storageBucket: 'my-web-app-cc2b0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1zZKBqkgFITtSlXvb6i53wlz_10_ObVA',
    appId: '1:887930857034:android:e9ff99f5c94a7b56e628b3',
    messagingSenderId: '887930857034',
    projectId: 'my-web-app-cc2b0',
    databaseURL: 'https://my-web-app-cc2b0-default-rtdb.firebaseio.com',
    storageBucket: 'my-web-app-cc2b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDozlHahgGEy_UygmZwAsOhHSznawsMxUc',
    appId: '1:887930857034:ios:1488b42b6fc898f2e628b3',
    messagingSenderId: '887930857034',
    projectId: 'my-web-app-cc2b0',
    databaseURL: 'https://my-web-app-cc2b0-default-rtdb.firebaseio.com',
    storageBucket: 'my-web-app-cc2b0.appspot.com',
    iosClientId: '887930857034-74u41kh06v1j8g3ongqvoq8s4kh3hdjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDozlHahgGEy_UygmZwAsOhHSznawsMxUc',
    appId: '1:887930857034:ios:1488b42b6fc898f2e628b3',
    messagingSenderId: '887930857034',
    projectId: 'my-web-app-cc2b0',
    databaseURL: 'https://my-web-app-cc2b0-default-rtdb.firebaseio.com',
    storageBucket: 'my-web-app-cc2b0.appspot.com',
    iosClientId: '887930857034-74u41kh06v1j8g3ongqvoq8s4kh3hdjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fileManager',
  );
}
